# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shortener.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'shortener.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fshortener.proto\x12\tshortener\"$\n\x0eResolveRequest\x12\x12\n\nshort_code\x18\x01 \x01(\t\"J\n\x0fResolveResponse\x12\x14\n\x0coriginal_url\x18\x01 \x01(\t\x12\x0e\n\x06url_id\x18\x02 \x01(\t\x12\x11\n\tis_active\x18\x03 \x01(\x08\x32W\n\x10ShortenerService\x12\x43\n\nResolveURL\x12\x19.shortener.ResolveRequest\x1a\x1a.shortener.ResolveResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shortener_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESOLVEREQUEST']._serialized_start=30
  _globals['_RESOLVEREQUEST']._serialized_end=66
  _globals['_RESOLVERESPONSE']._serialized_start=68
  _globals['_RESOLVERESPONSE']._serialized_end=142
  _globals['_SHORTENERSERVICE']._serialized_start=144
  _globals['_SHORTENERSERVICE']._serialized_end=231
# @@protoc_insertion_point(module_scope)
