upstream auth_service {
    server auth-service:8001;
}

upstream shortener_service {
    server shortener-service:8002;
}

upstream redirect_service {
    server redirect-service:8003;
}

upstream analytics_service {
    server analytics-service:8004;
}

limit_req_zone $binary_remote_addr zone=redirect_limit:10m rate=30r/s;

server {
    listen 80;
    server_name _;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    location /api/auth/ {
        proxy_pass http://auth_service/;
    }

    location /api/urls/ {
        proxy_pass http://shortener_service/;
    }

    location /api/analytics/ {
        proxy_pass http://analytics_service/;
    }

    # Redirect service (short links) — fallback, rate-limited
    location / {
        limit_req zone=redirect_limit burst=50 nodelay;
        proxy_pass http://redirect_service;
    }
}
